env:
  es6: true
  node: true
parserOptions:
  sourceType: script
rules:
  linebreak-style: [error, unix]
  max-len: [error, { code: 120, tabWidth: 2 }]
  # Safeguard from accidental use of = instead of === within conditions
  no-cond-assign: [error, except-parens]
  no-multi-spaces: off
  no-param-reassign: [error, { props: false }]
  no-unused-vars: [warn, { args: none }]
  object-curly-newline: [error, { multiline: true, consistent: true }]
  strict: [error, global]
